services:

  voting-managmentdb:
    container_name: voting-managmentDB
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: votingmanagmentdb
    extends:
      file: common-config.yml
      service: microservice-db-config


  configserver:
    image: "akermiyahia/configserver:v2-rabbitmq-mysql"
    container_name: configserver-voting-app
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  voting-managment:
    image: "akermiyahia/vm-ms:v2-rabbitmq-mysql"
    container_name: vm-ms
    ports:
      - "8080:8080"
    depends_on:
      voting-managmentdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "vm-ms"
      SPRING_DATASOURCE_URL: "jdbc:mysql://voting-managmentdb:3306/votingmanagmentdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    extends:
      file :  common-config.yml
      service: microservice-configserver-config

  voting:
    image: "akermiyahia/voting-ms:v2-rabbitmq-mysql"
    container_name: voting-ms
    ports:
      - "8081:8081"
    depends_on:
     configserver:
       condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "voting-ms"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  yahia-ORG:
    driver: "bridge"