server:
  port: 8080
spring:
  application:
    name: vm-ms
  datasource:
    url: jdbc:mysql://localhost:3306/votingmanagmentdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: "prod"


#---------------- eureka properties
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

  # infos that are going to be displayed in eureka dashboard
info:
 app :
  name: "votingmanagement"
  description: "here we handle condidate application sessions and voting sessions "
  version: "1.0.0"

#------------ end eureka properties


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
endpoints:
  shutdown:
    enabled: true


geolocation:
  api:
    url: http://ip-api.com/json

voting-managment:
  message: "Welcome to Voting managment service related local APIs"
  contactDetails:
    name: "Akermi yahia - Engineer"
    email: "ya.akermi@esi-sba.dz"
  onCallSupport:
    - (213) 540-752-251
    - (213) 661-161-378
logging:
  level:
    com:
      yahia:
        vmms: DEBUG

