services:

  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL","redis-cli ping | grep PONG"]
      timeout: 10s
      retries: 10
    extends:
      file: common-config.yml
      service: network-deploy-service

  voting-managmentdb:
    container_name: voting-managmentDB
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: votingmanagmentdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "akermiyahia/configserver:v5"
    container_name: configserver-voting-app
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config


  eurekaserver:
    image: "akermiyahia/eurekaserver:v5"
    container_name: eurekaserver-voting-app
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  voting-managment:
    image: "akermiyahia/vm-ms:v5"
    container_name: vm-ms
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      voting-managmentdb:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "vm-ms"
      SPRING_DATASOURCE_URL: "jdbc:mysql://voting-managmentdb:3306/votingmanagmentdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    extends:
      file :  common-config.yml
      service: microservice-eureka-config

  voting:
    image: "akermiyahia/voting-ms:v5"
    container_name: voting-ms
    ports:
      - "8081:8081"
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "voting-ms"
    extends:
      file :  common-config.yml
      service: microservice-eureka-config

  gatewayserver:
    image: "akermiyahia/gatewayserver:v5"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      voting-managment:
        condition: service_healthy
      voting:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
      SPRING_DATA_REDIS_TIMEOUT: 1s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  yahia-ORG:
    driver: "bridge"