server:
  port: 8081
spring:
  application:
    name: voting-ms
  data:
    mongodb:
      uri: mongodb+srv://yaakermi:uMOhzWo3hutWNHMW@voting-sys.a2zkg.mongodb.net/?retryWrites=true&w=majority&appName=voting-sys
      database: votingdb
  config:
    import: "optional:configserver:http://localhost:8071/"
  profiles:
    active: "prod"

#---------------- eureka properties
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

  # infos that are going to be displayed in eureka dashboard
info:
  app :
    name: "voting"
    description: "here we handle how users cast votes "
    version: "1.0.0"

#------------ end eureka properties



management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true

  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true





logging:
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG  # Logs MongoDB queries and operations
          database: INFO  # Change 'votingdb' to a valid log level like 'INFO'

voting-ms:
  message: "Welcome to Vote service related local APIs"
  contactDetails:
    name: "Akermi yahia - Engineer"
    email: "ya.akermi@esi-sba.dz"
  onCallSupport:
    - (213) 540-752-251
    - (213) 661-161-378
